"""
Export functions — write point data in cpc_all-compatible format, organized by year.

Output structure per year:
  raw/                        - clean source images (COPIED from import, never moved)
  ids/
    sam_click_prompts.json    - SAM3 click prompt format
    point_coords.csv          - flat CSV of all points (source="ocr")
  test_pts/                   - overlay images with crosshair + labels
  log.txt                     - processing log
  dataset_summary.txt         - generated by summarize.py
"""

import csv
import json
import os
import shutil

from PIL import Image, ImageDraw, ImageFont


# ── Font loading (shared with test image generation) ─────────────────

def _load_fonts(size_large=48, size_small=28):
    """Load fonts for test_pts overlay, matching cpc_reader style."""
    for font_path in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    ]:
        if os.path.exists(font_path):
            try:
                return (
                    ImageFont.truetype(font_path, size_large),
                    ImageFont.truetype(font_path, size_small),
                )
            except Exception:
                pass
    return ImageFont.load_default(), ImageFont.load_default()


# ── Test image generation ────────────────────────────────────────────

def generate_test_image(image_path, points, output_path):
    """Draw point annotations on raw image for visual verification.

    Each point gets (layered bottom to top):
      - Red crosshair at point (x, y)
      - Red large letter label in black box above
      - Yellow hollow circle over crosshair center
      - Yellow centroid dot
      - Small yellow letter label next to circle on black background
      - Yellow species code below crosshair on black background
    """
    img = Image.open(image_path)
    draw = ImageDraw.Draw(img)
    font, font_small, font_tiny = _load_fonts_3(48, 28, 18)
    cross_size = 20
    circle_r = 12

    pink = (255, 105, 180)

    for pt in points:
        x, y = pt['x'], pt['y']
        label = pt['label']
        species = pt.get('species_code', '') or pt.get('species', '')
        is_added = pt.get('added', False)

        # Color: pink for manually added points, red for OCR
        color = pink if is_added else "red"

        # Crosshair
        draw.line([(x - cross_size, y), (x + cross_size, y)], fill=color, width=3)
        draw.line([(x, y - cross_size), (x, y + cross_size)], fill=color, width=3)

        # Large letter label above
        text_x = x - 12
        text_y = y - cross_size - 54
        bbox = draw.textbbox((text_x, text_y), label, font=font)
        draw.rectangle(
            [bbox[0] - 2, bbox[1] - 2, bbox[2] + 2, bbox[3] + 2],
            fill=(0, 0, 0, 180),
        )
        draw.text((text_x, text_y), label, fill=color, font=font)

        # Hollow circle centered on crosshair
        circle_color = pink if is_added else "yellow"
        draw.ellipse(
            [x - circle_r, y - circle_r, x + circle_r, y + circle_r],
            outline=circle_color, width=2,
        )
        # Centroid dot
        draw.ellipse([x - 3, y - 3, x + 3, y + 3], fill=circle_color)

        # Small letter label next to circle
        lbl_x = x + circle_r + 4
        lbl_y = y - 9
        bbox_l = draw.textbbox((lbl_x, lbl_y), label, font=font_tiny)
        draw.rectangle(
            [bbox_l[0] - 1, bbox_l[1] - 1, bbox_l[2] + 1, bbox_l[3] + 1],
            fill=(0, 0, 0, 160),
        )
        draw.text((lbl_x, lbl_y), label, fill=circle_color, font=font_tiny)

        # Species code below crosshair
        if species:
            sp_y = y + cross_size + 4
            sp_color = pink if is_added else "yellow"
            bbox2 = draw.textbbox((text_x, sp_y), species, font=font_small)
            draw.rectangle(
                [bbox2[0] - 1, bbox2[1] - 1, bbox2[2] + 1, bbox2[3] + 1],
                fill=(0, 0, 0, 180),
            )
            draw.text((text_x, sp_y), species, fill=sp_color, font=font_small)

    img.save(output_path, quality=92)


def _load_fonts_3(size_large=48, size_small=28, size_tiny=20):
    """Load three font sizes for test image overlays."""
    for font_path in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    ]:
        if os.path.exists(font_path):
            try:
                return (
                    ImageFont.truetype(font_path, size_large),
                    ImageFont.truetype(font_path, size_small),
                    ImageFont.truetype(font_path, size_tiny),
                )
            except Exception:
                pass
    d = ImageFont.load_default()
    return d, d, d


# ── SAM click prompts JSON ───────────────────────────────────────────

def build_sam_entry(raw_filename, points):
    """Build a single entry for sam_click_prompts.json.

    Matches cpc_all format: {raw_image, points: [{label, species,
    name, category, x, y, point_type}]}
    Manually added points include 'added': true.
    """
    sam_points = []
    for pt in points:
        sp = {
            'label': pt['label'],
            'species': pt.get('species_code', ''),
            'name': pt.get('species_name', ''),
            'category': pt.get('category', ''),
            'x': pt['x'],
            'y': pt['y'],
            'point_type': 1,
        }
        if pt.get('added'):
            sp['added'] = True
        sam_points.append(sp)
    return {
        'raw_image': f"raw/{raw_filename}",
        'points': sam_points,
    }


def build_csv_row(raw_filename, pt):
    """Build a single CSV row matching cpc_all format (8 columns)."""
    return {
        'raw_image': raw_filename,
        'label': pt['label'],
        'species_code': pt.get('species_code', ''),
        'species_name': pt.get('species_name', ''),
        'category': pt.get('category', ''),
        'x': pt['x'],
        'y': pt['y'],
        'source': 'manual' if pt.get('added') else 'ocr',
    }


# ── Batch export ─────────────────────────────────────────────────────

CSV_FIELDNAMES = [
    'raw_image', 'label', 'species_code', 'species_name',
    'category', 'x', 'y', 'source',
]


def export_batch(detections, export_dir, log_fn=None):
    """Export a batch of detections to year-organized output.

    Args:
        detections: list of detection dicts, each with:
            {filename, pts_path, raw_path, points, year, date_str, site, t_id}
            where points is a list of point dicts with:
            {label, x, y, species_code, species_name, category, ...}
        export_dir: root export directory (year subdirs created within)
        log_fn: optional callable(msg) for logging

    Returns:
        dict with export stats: {exported_raw, exported_pts, point_records,
                                  test_images, years_affected}
    """
    if log_fn is None:
        log_fn = lambda msg: None

    # Group detections by year
    by_year = {}
    for det in detections:
        yr = det['year']
        by_year.setdefault(yr, []).append(det)

    stats = {
        'exported_raw': 0,
        'exported_pts': 0,
        'point_records': 0,
        'test_images': 0,
        'years_affected': set(),
    }

    for year, year_dets in sorted(by_year.items()):
        year_dir = os.path.join(export_dir, str(year))
        raw_dir = os.path.join(year_dir, 'raw')
        ids_dir = os.path.join(year_dir, 'ids')
        test_dir = os.path.join(year_dir, 'test_pts')
        os.makedirs(raw_dir, exist_ok=True)
        os.makedirs(ids_dir, exist_ok=True)
        os.makedirs(test_dir, exist_ok=True)

        stats['years_affected'].add(year)

        # Load existing SAM prompts to merge into
        sam_path = os.path.join(ids_dir, 'sam_click_prompts.json')
        sam_data = {}
        if os.path.exists(sam_path):
            with open(sam_path) as f:
                sam_data = json.load(f)

        csv_rows = []

        for det in year_dets:
            from scanner import pts_to_raw_name
            raw_name = pts_to_raw_name(det['filename'])
            raw_src = det.get('raw_path')
            points = det['points']

            # Copy raw image (READ from import, WRITE to export)
            if raw_src and os.path.exists(raw_src):
                dst = os.path.join(raw_dir, raw_name)
                if not os.path.exists(dst):
                    shutil.copy2(raw_src, dst)
                stats['exported_raw'] += 1

            # Build SAM entry
            sam_data[raw_name] = build_sam_entry(raw_name, points)

            # Build CSV rows
            for pt in points:
                csv_rows.append(build_csv_row(raw_name, pt))

            # Generate test_pts overlay on raw image
            raw_dst = os.path.join(raw_dir, raw_name)
            stem = os.path.splitext(raw_name)[0]
            test_out = os.path.join(test_dir, f"{stem}_test.jpg")
            if os.path.exists(raw_dst) and not os.path.exists(test_out):
                try:
                    generate_test_image(raw_dst, points, test_out)
                    stats['test_images'] += 1
                except Exception as e:
                    log_fn(f"  WARNING: test_pts failed for {raw_name}: {e}")

        # Write SAM prompts (full rewrite for this year)
        with open(sam_path, 'w') as f:
            json.dump(sam_data, f, indent=2)

        # Append CSV rows
        csv_path = os.path.join(ids_dir, 'point_coords.csv')
        write_header = not os.path.exists(csv_path)
        with open(csv_path, 'a', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=CSV_FIELDNAMES)
            if write_header:
                writer.writeheader()
            writer.writerows(csv_rows)

        stats['point_records'] += len(csv_rows)
        stats['exported_pts'] += len(year_dets)

        log_fn(f"  Year {year}: {len(year_dets)} images, "
               f"{len(csv_rows)} points exported")

    stats['years_affected'] = sorted(stats['years_affected'])
    return stats
